# Not yet tested
services:
  database:
    image: postgres:latest
    container_name: navyojan-postgres-db-server
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - ./database/docker-postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Kolkata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}'"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - navyojan-app

  backend:
    container_name: navyojan-backend-server
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 7000:8000
    env_file:
      - .env
    depends_on:
      - database
    working_dir: /navyojan-project
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 --noreload"
    environment:
      - TZ=Asia/Kolkata
      - POSTGRES_HOST=navyojan-postgres-db-server
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - navyojan-app

networks:
  navyojan-app:

volumes:
  logs-volumes:
