# Generated by Django 5.0.7 on 2024-09-09 15:25

import django.contrib.postgres.fields
import django.db.models.deletion
import userapp.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_type', models.CharField(choices=[('regular', 'Regular'), ('google', 'Google')], max_length=7, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_number_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=5)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScholarshipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('eligibility', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=None, null=True, size=None)),
                ('document_needed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=20, null=True), blank=True, default=None, null=True, size=None)),
                ('how_to_apply', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=None, null=True, size=None)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('published_on', models.DateField(blank=True, default=None, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('deadline', models.DateField(blank=True, default=None, null=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='scholarships', to='userapp.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('certificate_tenth', models.FileField(blank=True, upload_to='tenth_pdfs/', validators=[userapp.validators.validate_pdf])),
                ('certificate_inter', models.FileField(blank=True, upload_to='inter_pdfs/', validators=[userapp.validators.validate_pdf])),
                ('certificate_disability', models.FileField(blank=True, upload_to='disability_pdfs/', validators=[userapp.validators.validate_pdf])),
                ('certificate_sports', models.FileField(blank=True, upload_to='sports_pdfs/', validators=[userapp.validators.validate_pdf])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('categories', models.ManyToManyField(related_name='users', to='userapp.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfileScholarshipProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('organisation', models.CharField(blank=True, max_length=40)),
                ('org_site', models.URLField(blank=True)),
                ('can_host_scholarships', models.BooleanField(default=False)),
                ('hosted_scholarships', models.ManyToManyField(related_name='host', to='userapp.scholarshipdata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('baseuserprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userapp.baseuserprofile')),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('is_reviewer', models.BooleanField(default=False)),
                ('is_host_user', models.BooleanField(default=False)),
                ('free_account_privilages', models.BooleanField(default=True)),
                ('premium_account_privilages', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('userapp.baseuserprofile',),
        ),
        migrations.CreateModel(
            name='UserScholarshipApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_interested', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='userapp.scholarshipdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scholarship')},
            },
        ),
    ]
