# Generated by Django 5.0.7 on 2024-09-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipdata',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
