# Generated by Django 5.0.6 on 2024-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userscholarshipsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipdata',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userscholarshipsdata',
            name='status',
            field=models.CharField(choices=[('Interested', 'Interested'), ('Applied', 'Applied'), ('Interested and Applied', 'Interested and Applied'), ('Seen', 'Seen')], default='Seen', max_length=40),
        ),
    ]
