# Generated by Django 5.0.6 on 2024-09-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_scholarshipdata_document_needed_and_more'),
        ('userapp', '0002_scholarshipdata_is_approved'),
    ]

    operations = [
    ]
