# Generated by Django 5.0.6 on 2024-09-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_merge_20240916_1910'),
        ('userapp', '0003_merge_20240916_2102'),
    ]

    operations = [
    ]
