# Generated by Django 5.0.7 on 2024-08-02 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_scholarshipdata_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipdata',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipdata',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('google', 'Google')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='UserScholarshipApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_interested', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='userapp.scholarshipdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scholarship')},
            },
        ),
        migrations.DeleteModel(
            name='UserScholarshipsData',
        ),
    ]
