# Generated by Django 5.0.6 on 2024-09-16 18:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_merge_20240916_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipdata',
            name='document_needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=512, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='eligibility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='how_to_apply',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
