# Generated by Django 5.0.7 on 2024-09-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_userscholarshipstatus'),
        ('userapp', '0005_alter_scholarshipdata_document_needed_and_more'),
    ]

    operations = [
    ]
