# Generated by Django 5.0.6 on 2024-08-05 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_userprofile_free_account_privilages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(choices=[('MERIT', 'Merit'), ('FEMALE', 'Female'), ('MALE', 'Male'), ('SPORTS', 'Sports'), ('COLLEGE LEVEL', 'College Level'), ('MINORITIES', 'Minorities'), ('TALENT BASED', 'Talent Based'), ('DIFFERENTLY ABLED', 'Differently Abled'), ('SCHOOL LEVEL', 'School Level')], max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='scholarshipdata',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='scholarshipdata',
            name='description',
        ),
        migrations.AddField(
            model_name='scholarshipdata',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipdata',
            name='document_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipdata',
            name='how_to_apply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipdata',
            name='published_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scholarshipdata',
            name='state',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='others', max_length=10),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='link',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='scholarshipdata',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='scholarships', to='userapp.category'),
        ),
    ]
