# Generated by Django 5.0.6 on 2024-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_category_remove_scholarshipdata_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipdata',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='published_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
