# Generated by Django 5.0.7 on 2024-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_userprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='scholarshipdata',
            name='document_needed',
        ),
        migrations.RemoveField(
            model_name='scholarshipdata',
            name='eligibility',
        ),
        migrations.AddField(
            model_name='scholarshipdata',
            name='document_needed',
            field=models.ManyToManyField(blank=True, related_name='scholarships', to='userapp.documents'),
        ),
        migrations.AddField(
            model_name='scholarshipdata',
            name='eligibility',
            field=models.ManyToManyField(blank=True, related_name='scholarships', to='userapp.eligibility'),
        ),
    ]
