# Generated by Django 5.0.7 on 2024-09-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_documents_eligibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscholarshipapplicationdata',
            name='is_applied',
        ),
        migrations.RemoveField(
            model_name='userscholarshipapplicationdata',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='userscholarshipapplicationdata',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=10),
        ),
    ]
