# Generated by Django 5.0.6 on 2024-08-17 22:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_scholarshipdata_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipdata',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='document_needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, null=True), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='eligibility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scholarshipdata',
            name='how_to_apply',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, default=None, null=True, size=None),
        ),
    ]
