# Generated by Django 5.0.6 on 2024-08-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_scholarshipdata_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipdata',
            name='amount',
            field=models.CharField(blank=True, null=True),
        ),
    ]
