# Generated by Django 5.0.6 on 2024-08-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_scholarshipdata_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipdata',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
