# Generated by Django 5.0.6 on 2024-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_scholarshipdata_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipdata',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
