# Generated by Django 5.0.7 on 2024-11-18 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='otp',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')]),
        ),
    ]
