# Generated by Django 5.0.6 on 2024-11-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_verification_delete_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscholarshipapplicationdata',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('eligible', 'Eligible')], default='applied', max_length=10),
        ),
    ]
