# Generated by Django 5.0.7 on 2024-11-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_questions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuserprofile',
            old_name='pin_code',
            new_name='pincode',
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('financial_personal', ' Financial and Personal'), ('ambition_problems_challenges', 'Ambitions, Problems, and Challenges'), ('scholarship_details', 'Scholarship Details'), ('review_and_submit', 'Review and Submit')], max_length=50),
        ),
    ]
