# Generated by Django 5.0.6 on 2024-11-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_userdocumentsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentsummary',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
