# Generated by Django 5.0.6 on 2024-11-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_rename_pin_code_baseuserprofile_pincode_and_more'),
        ('userapp', '0019_userdocumentsummary_percentage'),
    ]

    operations = [
    ]
