# Generated by Django 5.0.6 on 2024-12-30 19:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_merge_20241127_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('standard_1_5', 'Standard 1-5'), ('standard_6_10', 'Standard 6-10'), ('higher_secondary', 'Higher Secondary'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('phd', 'PhD')], max_length=20),
        ),
    ]
