# Generated by Django 5.0.7 on 2025-01-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_alter_userprofile_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
