from .user import UserDisplaySerializer,UserScholarshipStatusSerializer,UserProfileSerializer, UserSerializer, LoginSerializer, UserDocumentsSerializer,UserPreferencesSerializer,UserProfileScholarshipProviderSerializer
from .scholarships import ScholarshipDataSerializer,UserScholarshipDataSerializer, CategorySerializer,DocumentSerializer,EligibilitySerializer
