name: Navyojan Automation

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to Droplet
        run: |
          ssh root@159.65.158.135 '
            cd navyojan_server &&
            sudo docker-compose down &&
            git pull origin dev &&
            sudo docker-compose up -d --build
          '
